# Generated by Django 4.2.25 on 2026-06-09 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_guest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bookingpayment',
            index=models.Index(fields=['status', '-created_at'], name='bookings_bo_status_54e78d_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingpayment',
            index=models.Index(fields=['booking', 'status'], name='bookings_bo_booking_7d458c_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['guest', '-created_at'], name='bookings_bo_guest_i_75f949_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['owner', '-created_at'], name='bookings_bo_owner_i_4a6f2c_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_bo_status_233e96_idx'),
        ),
    ]
