# Generated by Django 4.2.25 on 2025-12-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_bookingpayment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpayment',
            name='campay_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
