# Generated by Django 4.2.25 on 2026-02-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_bookingpayment_campay_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='bookingpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='bookingpayment',
            index=models.Index(fields=['status', '-created_at'], name='bookings_bo_status_54e78d_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingpayment',
            index=models.Index(fields=['booking', 'status'], name='bookings_bo_booking_7d458c_idx'),
        ),
    ]
