# Generated by Django 4.2.25 on 2026-02-04 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_bookingpayment_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingReview',
        ),
    ]
