# Generated by Django 4.2.25 on 2025-11-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0005_remove_user_is_staff_remove_user_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('guest', 'Guest'), ('owner', 'Owner'), ('Management', 'Management')], default='guest', max_length=10),
        ),
    ]
