# Generated by Django 4.2.25 on 2025-11-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('guest', 'Guest'), ('owner', 'Owner'), ('management', 'Management')], default='guest', max_length=10),
        ),
    ]
