# Generated by Django 4.2.25 on 2025-11-11 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0010_alter_user_managers_remove_user_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
