# Generated by Django 4.2.25 on 2025-11-11 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0012_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
