# Generated by Django 4.2.25 on 2025-11-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0015_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
