# Generated by Django 4.2.25 on 2025-11-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0016_user_phone_number_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=225, null=True, upload_to='profiles/'),
        ),
    ]
