# Generated by Django 4.2.25 on 2025-11-18 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0017_alter_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
