# Generated by Django 4.2.25 on 2025-11-21 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0018_remove_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
