# Generated by Django 4.2.25 on 2025-11-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0019_remove_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('owner', 'Owner'), ('management', 'Management')], max_length=10),
        ),
    ]
