# Generated by Django 4.2.25 on 2026-01-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_created', 'Booking Created'), ('booking_confirmed', 'Booking Confirmed'), ('booking_rejected', 'Booking Rejected'), ('booking_cancelled', 'Booking Cancelled'), ('payment_completed', 'Payment Completed'), ('payment_failed', 'Payment Failed'), ('payment_refunded', 'Payment Refunded'), ('car_verified', 'Car Verified'), ('car_rejected', 'Car Rejected'), ('booking_completed', 'Booking Completed'), ('review_received', 'Review Received'), ('payout_requested', 'Payout Requested'), ('payout_approved', 'Payout Approved'), ('payout_completed', 'Payout Completed'), ('payout_rejected', 'Payout Rejected')], max_length=50),
        ),
    ]
