# Generated by Django 4.2.25 on 2025-11-11 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0002_alter_managementprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_management_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
