# Generated by Django 4.2.25 on 2025-11-14 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_managementprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managementprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='managementprofile',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='managementprofile',
            name='phone',
        ),
    ]
