# Generated by Django 4.2.25 on 2025-11-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_remove_managementprofile_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/management/'),
        ),
    ]
