# Generated by Django 4.2.25 on 2025-11-14 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_alter_ownerprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerprofile',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='tax_id',
        ),
    ]
