# Generated by Django 4.2.25 on 2025-11-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_remove_ownerprofile_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/owner/'),
        ),
    ]
