# Generated by Django 4.2.25 on 2026-01-12 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_bookingpayment_campay_reference_and_more'),
        ('payments', '0002_alter_paymenttransaction_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owner_payout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refunded_platform', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refunded_owner', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking_payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='bookings.bookingpayment')),
            ],
        ),
    ]
