# Generated by Django 4.2.25 on 2026-06-09 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'role': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='availability',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='listings.car'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['owner', 'status'], name='listings_ca_owner_i_c06eea_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['status', 'is_verified'], name='listings_ca_status_df2cba_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['-created_at'], name='listings_ca_created_8d0f1d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('car', 'date')},
        ),
    ]
