# Generated by Django 4.2.25 on 2025-12-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_car_daily_rate_car_status_alter_carphoto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
