# Generated by Django 4.2.25 on 2025-12-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_car_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('maintenance', 'Under Maintenance'), ('inactive', 'Inactive')], default='available', max_length=20),
        ),
    ]
