# Generated by Django 4.2.25 on 2026-02-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_car_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='avg_rating',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('maintenance', 'Under Maintenance'), ('inactive', 'Inactive')], db_index=True, default='available', max_length=20),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['owner', 'status'], name='listings_ca_owner_i_c06eea_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['status', 'is_verified'], name='listings_ca_status_df2cba_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['-created_at'], name='listings_ca_created_8d0f1d_idx'),
        ),
    ]
