# Generated by Django 4.2.25 on 2025-11-11 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('license_expiry', models.CharField(blank=True, max_length=30)),
                ('preferred_payment', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(default='Active', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_guest_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
