# Generated by Django 4.2.25 on 2025-11-14 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0004_alter_guestprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestprofile',
            name='license_expiry',
        ),
        migrations.RemoveField(
            model_name='guestprofile',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='guestprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='guestprofile',
            name='preferred_payment',
        ),
    ]
