# Generated by Django 4.2.25 on 2025-11-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0005_remove_guestprofile_license_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/guest/'),
        ),
    ]
